services:
  app:
    image: 'driver-service:latest'
    build:
      dockerfile: Dockerfile
    container_name: driver-service
    depends_on:
      - drivers_db
    networks:
      - microservices-network
    ports:
      - "8082:8080"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  drivers_db:
    image: postgres:latest
    container_name: drivers_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    networks:
      - microservices-network
    volumes:
      - /var/lib/docker/volumes/drivers-db:/var/lib/postgresql/data

networks:
  microservices-network:
    external: true